USE [silPolygons]
GO

DECLARE @RC int

-- TODO: Set parameter values here.

EXECUTE [dbo].[InsertRandomPoints] 
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
EXECUTE [dbo].[InsertRandomPoints] ;
GO


