USE [master]
GO

/****** Object:  Database [silPolygons]    Script Date: 20.02.2018 20:03:41 ******/
CREATE DATABASE [silPolygons]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'silPolygons', FILENAME = N'C:\mssql\silPolygons.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'silPolygons_log', FILENAME = N'C:\mssql\silPolygons_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [silPolygons] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [silPolygons].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [silPolygons] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [silPolygons] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [silPolygons] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [silPolygons] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [silPolygons] SET ARITHABORT OFF 
GO

ALTER DATABASE [silPolygons] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [silPolygons] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [silPolygons] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [silPolygons] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [silPolygons] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [silPolygons] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [silPolygons] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [silPolygons] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [silPolygons] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [silPolygons] SET  DISABLE_BROKER 
GO

ALTER DATABASE [silPolygons] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [silPolygons] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [silPolygons] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [silPolygons] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [silPolygons] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [silPolygons] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [silPolygons] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [silPolygons] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [silPolygons] SET  MULTI_USER 
GO

ALTER DATABASE [silPolygons] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [silPolygons] SET DB_CHAINING OFF 
GO

ALTER DATABASE [silPolygons] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [silPolygons] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [silPolygons] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [silPolygons] SET  READ_WRITE 
GO


USE [silPolygons]
GO

/****** Object:  Table [dbo].[point]    Script Date: 20.02.2018 20:04:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[point](
	[x] [real] NOT NULL,
	[y] [real] NOT NULL,
	[PointsId] [smallint] IDENTITY(1,1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PointsId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

